version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es_dev
    environment:
      # Rất quan trọng: Báo cho ES biết đây là 1 node duy nhất
      - discovery.type=single-node
      # Tắt bảo mật (username/password) cho môi trường dev
      - xpack.security.enabled=false
      # !!! QUAN TRỌNG CHO MÁY YẾU !!!
      # Giới hạn RAM. Đặt 512m cho máy yếu, 1g (1GB) nếu bạn có 16GB RAM
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    # Dịch vụ 2: Kibana (Giao diện web để xem dữ liệu)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana-dev
    environment:
        # Báo cho Kibana biết ES đang ở đâu
        # 'elasticsearch' là tên service ở trên, Docker tự phân giải
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
        # Mở cổng 5601 để bạn truy cập Kibana bằng trình duyệt
        - "5601:5601"
    depends_on:
        # Yêu cầu Docker phải khởi động ES xong rồi mới khởi động Kibana
      - elasticsearch
    networks:
        - elastic-net
volumes:
  esdata:
    driver: local

networks:
  elastic-net:
    driver: bridge